apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition
  namespace: crdb-chaos
spec:
  action: partition
  mode: one
  selector:
    labelSelectors:
      "app.kubernetes.io/instance": "crdb"
  direction: to
  target:
    selector:
      labelSelectors:
        "app.kubernetes.io/instance": "crdb"
    mode: one
  duration: "300s"
  scheduler:
    cron: "@every 10m"
