  
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-zero
  namespace: dgraph-chaos
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      "component": "zero"
  scheduler:
    cron: "@every 1m"